[build]
  publish = "build/"
  command = "yarn build"

  # Develop Branch Deploy context: All deploys that are not in
  # an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
  NODE_VERSION='9.10.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://kovan.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_PROD_IPFS_URL="https://ipfs.kleros.io"
  REACT_APP_PROD_S3_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/cfs"
  REACT_APP_PROD_T2CR_URL="https://tokens.kleros.io"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
  NODE_VERSION='9.10.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://mainnet.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_PROD_IPFS_URL="https://ipfs.kleros.io"
  REACT_APP_PROD_S3_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/cfs"
  REACT_APP_PROD_T2CR_URL="https://tokens.kleros.io"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
